data:
  dataset: "mnist"
  type: "md"
  root_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/data/multi_descriptive_MNIST/"

model_info:
  save_model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/mnist_md/dvae_v256_ds2/"
  save_model_name: "dvae"

model_params:
  in_channels: 3
  vocab_size: 256
  num_x2downsamples: 2
  num_resids_downsample: 4
  num_resids_bottleneck: 4
  hidden_dim: 256

training:
  NUM_EPOCHS: 30
  BATCH_SIZE: 32
  LR: 0.01
  LR_gamma: 0.1
  step_LR_milestones:
    - 5
    - 10
  temp_start: 5
  temp_end: 0.01
  temp_steps: 3000
  klU_type: fixed
  klU_const: 0.01
  klU_start: 0
  klU_end: 0.01
  klU_steps: 10000

