paths:
  save_model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/dvae/"
  save_model_name: "DVAE"
  root_img_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/data/triple_mnist/train"

model:
  in_channels: 1
  vocab_size: 64
  num_x2downsamples: 2
  num_resids_downsample: 2
  num_resids_bottleneck: 2

training:
  NUM_EPOCHS: 800
  BATCH_SIZE: 512
  LR: 0.0001
  LR_gamma: 0.35
  step_LR_milestones:
    - 50
    - 100
  temp_start: 1
  temp_end: 0.0625
  temp_steps: 1600
  KLD_lambda_start: 0
  KLD_lambda_end: 6
  KLD_lambda_steps: 800
