data:
  mnist_type: "classic_56"
  root_img_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/data/MNIST/"

model_paths:
  save_model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/mnist/dvae_vocab32_mnist56_100e/"
  save_model_name: "dvae_vocab32_mnist56"

model:
  in_channels: 1
  vocab_size: 32
  num_x2downsamples: 2
  num_resids_downsample: 3
  num_resids_bottleneck: 4
  hidden_dim: 256

training:
  NUM_EPOCHS: 100
  BATCH_SIZE: 256
  LR: 0.1
  LR_gamma: 0.1
  step_LR_milestones:
    - 10
    - 30
    - 60
  temp_start: 5
  temp_end: 0.01
  temp_steps: 3000
