data:
  mnist_type: "md"
  root_img_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/data/multi_descriptive_MNIST/"

model_paths:
  save_model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/mnist_md/dvae_v256_ds3/"
  save_model_name: "dvae"

model:
  in_channels: 3
  vocab_size: 256
  num_x2downsamples: 3
  num_resids_downsample: 3
  num_resids_bottleneck: 4
  hidden_dim: 256

training:
  NUM_EPOCHS: 100
  BATCH_SIZE: 64
  LR: 0.1
  LR_gamma: 0.1
  step_LR_milestones:
    - 5
    - 10
  temp_start: 5
  temp_end: 0.01
  temp_steps: 3000
  use_fixed_klU: false
  klU_const: 0.01
  use_anneal_klU: true
  klU_start: 0
  klU_end: 0.01
  klU_steps: 10000
