paths:
  save_model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/dvae_vocab64_tripleMnist/"
  save_model_name: "dvae_vocab64_tripleMnist"
  root_img_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/data/triple_mnist/train"

model:
  in_channels: 1
  vocab_size: 64
  num_x2downsamples: 2
  num_resids_downsample: 3
  num_resids_bottleneck: 4
  hidden_dim: 128

training:
  NUM_EPOCHS: 300
  BATCH_SIZE: 128
  LR: 0.001
  LR_gamma: 0.1
  step_LR_milestones:
    - 40
    - 80
  temp_start: 1
  temp_end: 0.0625
  temp_steps: 8000
  KLD_lambda_start: 0
  KLD_lambda_end: 0.01
  KLD_lambda_steps: 2500
