data:
  dataset: "cub"
  dataset_type: "32_text"
  custom_transform_version: 0
  root_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/data/CUB/"

model_info:
  save_model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/cub/dvae32_v512_ds2/"
  save_model_name: "dvae"

model_params:
  in_channels: 3
  vocab_size: 512
  num_x2downsamples: 2
  num_resids_downsample: 6
  num_resids_bottleneck: 4
  hidden_dim: 512

training:
  loss_fn: "mse"
  NUM_EPOCHS: 500
  BATCH_SIZE: 256
  LR: 0.001
  LR_gamma: 0.1
  step_LR_milestones:
    - 20
    - 120
  temp_start: 10
  temp_end: 0.01
  temp_steps: 20000
  klU_type: linear
  klU_const: 0.001
  klU_start: 0
  klU_end: 0.0001
  klU_steps: 18000

