data:
  dataset: "mnist"
  dataset_type: "md"
  root_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/data/multi_descriptive_MNIST/"

model_info:
  save_model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/mnist_md/matcher_v256_ds3/"
  save_model_name: "matcher"
  vae_model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/mnist_md/dvae_v256_ds3/"
  vae_model_name: "dvae"

model_params:
  in_channels: 3
  vocab_size: 256
  num_x2downsamples: 3
  num_resids_downsample: 4
  num_resids_bottleneck: 4
  hidden_dim: 256

training:
  NUM_EPOCHS: 100
  BATCH_SIZE: 32
  LR: 0.01
  LR_gamma: 0.1
  step_LR_milestones:
    - 5
    - 20

