data:
  dataset: "cub"
  dataset_type: "64_token_ids"
  custom_transform_version: 1
  root_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/data/CUB/"

model_info:
  model_type: "2s2s"
  model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/cub/Tr2s2s_cub64_v512_ds2_nb12_cnb8/"
  model_name: "generator"
  vae_model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/cub/dvae64_v512_ds2/"
  vae_model_name: "dvae"

image:
  in_channels: 3

latent:
  hidden_width: 16
  hidden_height: 16
  vocab_size: 512
  cond_seq_size: 66
  cond_vocab_size: 5452

model_params:
  num_x2downsamples: 2
  num_resids_downsample: 6
  num_resids_bottleneck: 4
  hidden_dim: 512
  num_blocks: 12
  cond_num_blocks: 8
  n_attn_heads: 8
  dropout_prob: 0.1

training:
  NUM_EPOCHS: 500
  BATCH_SIZE: 32
  ACCUMULATION_STEPS: 2
  LR: 0.001
  LR_gamma: 0.1
  step_LR_milestones:
    - 50
    - 300
