data:
  dataset: "mnist"
  type: "md"
  root_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/data/multi_descriptive_MNIST/"

model_info:
  type: "1s2s"
  model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/mnist_md/trArC1s2s_v256_ds2_nb12/"
  model_name: "generator"
  vae_model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/mnist_md/dvae_v256_ds2/"
  vae_model_name: "dvae"

image:
  in_channels: 3

latent:
  hidden_width: 32
  hidden_height: 32
  vocab_size: 256
  cond_seq_size: 12
  cond_vocab_size: 20

model_params:
  num_x2downsamples: 2
  num_resids_downsample: 4
  num_resids_bottleneck: 4
  hidden_dim: 256
  num_blocks: 12
  n_attn_heads: 8
  dropout_prob: 0.1

training:
  NUM_EPOCHS: 20
  BATCH_SIZE: 12
  LR: 0.001
  LR_gamma: 0.1
  step_LR_milestones:
    - 5
    - 10
