data:
  mnist_type: "md"
  root_img_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/data/multi_descriptive_MNIST/"

model_paths:
  model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/mnist_md/trArC2s_v256_ds3_nb12_cnb6/"
  model_name: "generator"
  vae_model_path: "/u/82/sukhoba1/unix/Desktop/TA-VQVAE/models/mnist_md/dvae_v256_ds3/"
  vae_model_name: "dvae"

image:
  in_channels: 3

latent:
  hidden_width: 16
  hidden_height: 16
  vocab_size: 256
  cond_seq_size: 12
  cond_vocab_size: 20

model:
  num_x2downsamples: 3
  num_resids_downsample: 3
  num_resids_bottleneck: 4
  hidden_dim: 256
  num_blocks: 12
  cond_num_blocks: 6
  n_attn_heads: 8
  dropout_prob: 0.1

training:
  NUM_EPOCHS: 30
  BATCH_SIZE: 32
  LR: 0.01
  LR_gamma: 0.1
  step_LR_milestones:
    - 5
    - 10
